import Head from 'next/head'
import { Crud } from '../src/components/crud/index'
import DataTable from '../src/components/DataTables'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DataTable/>
      <Crud/>
    </div>
  )
}
